{
  "uid" : "1faabcc4df7f3f7d",
  "name" : "Select a random card from \"Предложения\" group and compare UI vs BACKEND data.",
  "fullName" : "tests.test_speech_exercises_ru.TestCardsRU#test_random_cards_in_sentences_ru",
  "historyId" : "0c7f6c8c808a1acd373a8bdcd331af43",
  "time" : {
    "start" : 1728697356198,
    "stop" : 1728697356198,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556ffef7602a <unknown>\n#1 0x556ffec5c5e0 <unknown>\n#2 0x556ffec547eb <unknown>\n#3 0x556ffec44a09 <unknown>\n#4 0x556ffec46744 <unknown>\n#5 0x556ffec44cbd <unknown>\n#6 0x556ffec4452f <unknown>\n#7 0x556ffec44422 <unknown>\n#8 0x556ffec42493 <unknown>\n#9 0x556ffec42ada <unknown>\n#10 0x556ffec5ef41 <unknown>\n#11 0x556ffecf08c5 <unknown>\n#12 0x556ffecd0b22 <unknown>\n#13 0x556ffecefd7d <unknown>\n#14 0x556ffecd08c3 <unknown>\n#15 0x556ffec9e6b3 <unknown>\n#16 0x556ffec9f68e <unknown>\n#17 0x556ffef40a2b <unknown>\n#18 0x556ffef449b1 <unknown>\n#19 0x556ffef2d225 <unknown>\n#20 0x556ffef45532 <unknown>\n#21 0x556ffef1238f <unknown>\n#22 0x556ffef64f28 <unknown>\n#23 0x556ffef650f3 <unknown>\n#24 0x556ffef74e7c <unknown>\n#25 0x7fa4cda94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2b6082dd33bed915f0a37ef849230359\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f4df4eca960>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x556ffef650f3 \\\\u003Cunknown>\\\\n#24 0x556ffef74e7c \\\\u003Cunknown>\\\\n#25 0x7fa4cda94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x556ffef7602a <unknown>\nE       #1 0x556ffec5c5e0 <unknown>\nE       #2 0x556ffec547eb <unknown>\nE       #3 0x556ffec44a09 <unknown>\nE       #4 0x556ffec46744 <unknown>\nE       #5 0x556ffec44cbd <unknown>\nE       #6 0x556ffec4452f <unknown>\nE       #7 0x556ffec44422 <unknown>\nE       #8 0x556ffec42493 <unknown>\nE       #9 0x556ffec42ada <unknown>\nE       #10 0x556ffec5ef41 <unknown>\nE       #11 0x556ffecf08c5 <unknown>\nE       #12 0x556ffecd0b22 <unknown>\nE       #13 0x556ffecefd7d <unknown>\nE       #14 0x556ffecd08c3 <unknown>\nE       #15 0x556ffec9e6b3 <unknown>\nE       #16 0x556ffec9f68e <unknown>\nE       #17 0x556ffef40a2b <unknown>\nE       #18 0x556ffef449b1 <unknown>\nE       #19 0x556ffef2d225 <unknown>\nE       #20 0x556ffef45532 <unknown>\nE       #21 0x556ffef1238f <unknown>\nE       #22 0x556ffef64f28 <unknown>\nE       #23 0x556ffef650f3 <unknown>\nE       #24 0x556ffef74e7c <unknown>\nE       #25 0x7fa4cda94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728697356970,
      "stop" : 1728697357391,
      "duration" : 421
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556ffef7602a <unknown>\n#1 0x556ffec5c5e0 <unknown>\n#2 0x556ffec547eb <unknown>\n#3 0x556ffec44a09 <unknown>\n#4 0x556ffec46744 <unknown>\n#5 0x556ffec44cbd <unknown>\n#6 0x556ffec4452f <unknown>\n#7 0x556ffec44422 <unknown>\n#8 0x556ffec42493 <unknown>\n#9 0x556ffec42ada <unknown>\n#10 0x556ffec5ef41 <unknown>\n#11 0x556ffecf08c5 <unknown>\n#12 0x556ffecd0b22 <unknown>\n#13 0x556ffecefd7d <unknown>\n#14 0x556ffecd08c3 <unknown>\n#15 0x556ffec9e6b3 <unknown>\n#16 0x556ffec9f68e <unknown>\n#17 0x556ffef40a2b <unknown>\n#18 0x556ffef449b1 <unknown>\n#19 0x556ffef2d225 <unknown>\n#20 0x556ffef45532 <unknown>\n#21 0x556ffef1238f <unknown>\n#22 0x556ffef64f28 <unknown>\n#23 0x556ffef650f3 <unknown>\n#24 0x556ffef74e7c <unknown>\n#25 0x7fa4cda94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728697356970,
        "stop" : 1728697357391,
        "duration" : 421
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556ffef7602a <unknown>\n#1 0x556ffec5c5e0 <unknown>\n#2 0x556ffec547eb <unknown>\n#3 0x556ffec44a09 <unknown>\n#4 0x556ffec46744 <unknown>\n#5 0x556ffec44cbd <unknown>\n#6 0x556ffec4452f <unknown>\n#7 0x556ffec44422 <unknown>\n#8 0x556ffec42493 <unknown>\n#9 0x556ffec42ada <unknown>\n#10 0x556ffec5ef41 <unknown>\n#11 0x556ffecf08c5 <unknown>\n#12 0x556ffecd0b22 <unknown>\n#13 0x556ffecefd7d <unknown>\n#14 0x556ffecd08c3 <unknown>\n#15 0x556ffec9e6b3 <unknown>\n#16 0x556ffec9f68e <unknown>\n#17 0x556ffef40a2b <unknown>\n#18 0x556ffef449b1 <unknown>\n#19 0x556ffef2d225 <unknown>\n#20 0x556ffef45532 <unknown>\n#21 0x556ffef1238f <unknown>\n#22 0x556ffef64f28 <unknown>\n#23 0x556ffef650f3 <unknown>\n#24 0x556ffef74e7c <unknown>\n#25 0x7fa4cda94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"2b6082dd33bed915f0a37ef849230359\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "driver",
    "time" : {
      "start" : 1728697356199,
      "stop" : 1728697356969,
      "duration" : 770
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728697167335,
      "stop" : 1728697167335,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728697357423,
      "stop" : 1728697357485,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Речевые упражнения."
  }, {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsRU"
  }, {
    "name" : "host",
    "value" : "fv-az570-490"
  }, {
    "name" : "thread",
    "value" : "2304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_ru"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 7,
        "passed" : 53,
        "unknown" : 0,
        "total" : 60
      },
      "items" : [ {
        "uid" : "1585b46b77851b0f",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/1585b46b77851b0f",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x561e96b0d02a <unknown>\n#1 0x561e967f35e0 <unknown>\n#2 0x561e967eb7eb <unknown>\n#3 0x561e967dba09 <unknown>\n#4 0x561e967dd744 <unknown>\n#5 0x561e967dbcbd <unknown>\n#6 0x561e967db52f <unknown>\n#7 0x561e967db422 <unknown>\n#8 0x561e967d9493 <unknown>\n#9 0x561e967d9ada <unknown>\n#10 0x561e967f5f41 <unknown>\n#11 0x561e968878c5 <unknown>\n#12 0x561e96867b22 <unknown>\n#13 0x561e96886d7d <unknown>\n#14 0x561e968678c3 <unknown>\n#15 0x561e968356b3 <unknown>\n#16 0x561e9683668e <unknown>\n#17 0x561e96ad7a2b <unknown>\n#18 0x561e96adb9b1 <unknown>\n#19 0x561e96ac4225 <unknown>\n#20 0x561e96adc532 <unknown>\n#21 0x561e96aa938f <unknown>\n#22 0x561e96afbf28 <unknown>\n#23 0x561e96afc0f3 <unknown>\n#24 0x561e96b0be7c <unknown>\n#25 0x7f5156694ac3 <unknown>",
        "time" : {
          "start" : 1728611047436,
          "stop" : 1728611047436,
          "duration" : 0
        }
      }, {
        "uid" : "f3fc6438bfdf8219",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/f3fc6438bfdf8219",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525197914,
          "stop" : 1728525208619,
          "duration" : 10705
        }
      }, {
        "uid" : "80dc1256572b5a38",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/80dc1256572b5a38",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728438866316,
          "stop" : 1728438877419,
          "duration" : 11103
        }
      }, {
        "uid" : "a10bd4f079e2493c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/a10bd4f079e2493c",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352467716,
          "stop" : 1728352478163,
          "duration" : 10447
        }
      }, {
        "uid" : "b9d57f692b7aa84a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/b9d57f692b7aa84a",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267265833,
          "stop" : 1728267265833,
          "duration" : 0
        }
      }, {
        "uid" : "51a1ab722316b825",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/51a1ab722316b825",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728180006014,
          "stop" : 1728180016503,
          "duration" : 10489
        }
      }, {
        "uid" : "b8885ab990ca66c8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/b8885ab990ca66c8",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093280944,
          "stop" : 1728093292587,
          "duration" : 11643
        }
      }, {
        "uid" : "15e75f8895af5921",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/15e75f8895af5921",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728006984915,
          "stop" : 1728006997007,
          "duration" : 12092
        }
      }, {
        "uid" : "e3ae2747c57ba03a",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/e3ae2747c57ba03a",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727920741082,
          "stop" : 1727920753848,
          "duration" : 12766
        }
      }, {
        "uid" : "7430dab01e85aa98",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/7430dab01e85aa98",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727834122239,
          "stop" : 1727834134313,
          "duration" : 12074
        }
      }, {
        "uid" : "6353fefb7070cc3b",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/6353fefb7070cc3b",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727748235332,
          "stop" : 1727748248822,
          "duration" : 13490
        }
      }, {
        "uid" : "40872053e91db6d2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/40872053e91db6d2",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727661514796,
          "stop" : 1727661526265,
          "duration" : 11469
        }
      }, {
        "uid" : "b0ceb7b804a11315",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/b0ceb7b804a11315",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727575425498,
          "stop" : 1727575437747,
          "duration" : 12249
        }
      }, {
        "uid" : "3a5db4df0853d107",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/3a5db4df0853d107",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/2/series/4/exercise/1693 has not been changed!!!",
        "time" : {
          "start" : 1727488614674,
          "stop" : 1727488641751,
          "duration" : 27077
        }
      }, {
        "uid" : "30179de93b64c3de",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/30179de93b64c3de",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727402375995,
          "stop" : 1727402389709,
          "duration" : 13714
        }
      }, {
        "uid" : "91f307317cd760e",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/91f307317cd760e",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727315907967,
          "stop" : 1727315921721,
          "duration" : 13754
        }
      }, {
        "uid" : "bccdcb1f0fc0d194",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/bccdcb1f0fc0d194",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nKeyError: 'answerOptions'",
        "time" : {
          "start" : 1727229527773,
          "stop" : 1727229593335,
          "duration" : 65562
        }
      }, {
        "uid" : "6937676a8f346314",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/6937676a8f346314",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727142986281,
          "stop" : 1727142995960,
          "duration" : 9679
        }
      }, {
        "uid" : "e01b9a57048b2653",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/e01b9a57048b2653",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1727056386223,
          "stop" : 1727056386223,
          "duration" : 0
        }
      }, {
        "uid" : "1913af4be3f6017d",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/1913af4be3f6017d",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1726970304178,
          "stop" : 1726970313072,
          "duration" : 8894
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "1faabcc4df7f3f7d.json",
  "parameterValues" : [ ]
}