{
  "uid" : "34f54c83c5e8df92",
  "name" : "Select a random card from \"Группа слов\" group and compare UI vs BACKEND data.",
  "fullName" : "tests.test_speech_exercises_ru.TestCardsRU#test_random_cards_in_group_words_ru",
  "historyId" : "0c99feebb7314b5ff7efb452ee6dded7",
  "time" : {
    "start" : 1728697354904,
    "stop" : 1728697354904,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556d4d54502a <unknown>\n#1 0x556d4d22b5e0 <unknown>\n#2 0x556d4d2237eb <unknown>\n#3 0x556d4d213a09 <unknown>\n#4 0x556d4d215744 <unknown>\n#5 0x556d4d213cbd <unknown>\n#6 0x556d4d21352f <unknown>\n#7 0x556d4d213422 <unknown>\n#8 0x556d4d211493 <unknown>\n#9 0x556d4d211ada <unknown>\n#10 0x556d4d22df41 <unknown>\n#11 0x556d4d2bf8c5 <unknown>\n#12 0x556d4d29fb22 <unknown>\n#13 0x556d4d2bed7d <unknown>\n#14 0x556d4d29f8c3 <unknown>\n#15 0x556d4d26d6b3 <unknown>\n#16 0x556d4d26e68e <unknown>\n#17 0x556d4d50fa2b <unknown>\n#18 0x556d4d5139b1 <unknown>\n#19 0x556d4d4fc225 <unknown>\n#20 0x556d4d514532 <unknown>\n#21 0x556d4d4e138f <unknown>\n#22 0x556d4d533f28 <unknown>\n#23 0x556d4d5340f3 <unknown>\n#24 0x556d4d543e7c <unknown>\n#25 0x7fc4ace94ac3 <unknown>",
  "statusTrace" : "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"a6a7f766bfb45ce31967e836cc69d5f7\")>\n\n    @pytest.fixture()\n    @allure.step(f'Open page: {MainPageLinks.URL_MAIN_PAGE}')\n    def main_page_open(driver):\n>       driver.get(MainPageLinks.URL_MAIN_PAGE)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:353: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f4df4e20050>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#23 0x556d4d5340f3 \\\\u003Cunknown>\\\\n#24 0x556d4d543e7c \\\\u003Cunknown>\\\\n#25 0x7fc4ace94ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=129.0.6668.89)\nE       Stacktrace:\nE       #0 0x556d4d54502a <unknown>\nE       #1 0x556d4d22b5e0 <unknown>\nE       #2 0x556d4d2237eb <unknown>\nE       #3 0x556d4d213a09 <unknown>\nE       #4 0x556d4d215744 <unknown>\nE       #5 0x556d4d213cbd <unknown>\nE       #6 0x556d4d21352f <unknown>\nE       #7 0x556d4d213422 <unknown>\nE       #8 0x556d4d211493 <unknown>\nE       #9 0x556d4d211ada <unknown>\nE       #10 0x556d4d22df41 <unknown>\nE       #11 0x556d4d2bf8c5 <unknown>\nE       #12 0x556d4d29fb22 <unknown>\nE       #13 0x556d4d2bed7d <unknown>\nE       #14 0x556d4d29f8c3 <unknown>\nE       #15 0x556d4d26d6b3 <unknown>\nE       #16 0x556d4d26e68e <unknown>\nE       #17 0x556d4d50fa2b <unknown>\nE       #18 0x556d4d5139b1 <unknown>\nE       #19 0x556d4d4fc225 <unknown>\nE       #20 0x556d4d514532 <unknown>\nE       #21 0x556d4d4e138f <unknown>\nE       #22 0x556d4d533f28 <unknown>\nE       #23 0x556d4d5340f3 <unknown>\nE       #24 0x556d4d543e7c <unknown>\nE       #25 0x7fc4ace94ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "driver",
    "time" : {
      "start" : 1728697354905,
      "stop" : 1728697355680,
      "duration" : 775
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  }, {
    "name" : "main_page_open",
    "time" : {
      "start" : 1728697355680,
      "stop" : 1728697356102,
      "duration" : 422
    },
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556d4d54502a <unknown>\n#1 0x556d4d22b5e0 <unknown>\n#2 0x556d4d2237eb <unknown>\n#3 0x556d4d213a09 <unknown>\n#4 0x556d4d215744 <unknown>\n#5 0x556d4d213cbd <unknown>\n#6 0x556d4d21352f <unknown>\n#7 0x556d4d213422 <unknown>\n#8 0x556d4d211493 <unknown>\n#9 0x556d4d211ada <unknown>\n#10 0x556d4d22df41 <unknown>\n#11 0x556d4d2bf8c5 <unknown>\n#12 0x556d4d29fb22 <unknown>\n#13 0x556d4d2bed7d <unknown>\n#14 0x556d4d29f8c3 <unknown>\n#15 0x556d4d26d6b3 <unknown>\n#16 0x556d4d26e68e <unknown>\n#17 0x556d4d50fa2b <unknown>\n#18 0x556d4d5139b1 <unknown>\n#19 0x556d4d4fc225 <unknown>\n#20 0x556d4d514532 <unknown>\n#21 0x556d4d4e138f <unknown>\n#22 0x556d4d533f28 <unknown>\n#23 0x556d4d5340f3 <unknown>\n#24 0x556d4d543e7c <unknown>\n#25 0x7fc4ace94ac3 <unknown>\n\n",
    "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Open page: https://brainup.site/",
      "time" : {
        "start" : 1728697355680,
        "stop" : 1728697356101,
        "duration" : 421
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x556d4d54502a <unknown>\n#1 0x556d4d22b5e0 <unknown>\n#2 0x556d4d2237eb <unknown>\n#3 0x556d4d213a09 <unknown>\n#4 0x556d4d215744 <unknown>\n#5 0x556d4d213cbd <unknown>\n#6 0x556d4d21352f <unknown>\n#7 0x556d4d213422 <unknown>\n#8 0x556d4d211493 <unknown>\n#9 0x556d4d211ada <unknown>\n#10 0x556d4d22df41 <unknown>\n#11 0x556d4d2bf8c5 <unknown>\n#12 0x556d4d29fb22 <unknown>\n#13 0x556d4d2bed7d <unknown>\n#14 0x556d4d29f8c3 <unknown>\n#15 0x556d4d26d6b3 <unknown>\n#16 0x556d4d26e68e <unknown>\n#17 0x556d4d50fa2b <unknown>\n#18 0x556d4d5139b1 <unknown>\n#19 0x556d4d4fc225 <unknown>\n#20 0x556d4d514532 <unknown>\n#21 0x556d4d4e138f <unknown>\n#22 0x556d4d533f28 <unknown>\n#23 0x556d4d5340f3 <unknown>\n#24 0x556d4d543e7c <unknown>\n#25 0x7fc4ace94ac3 <unknown>\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/runner/work/auto-tests-python/auto-tests-python/tests/conftest.py\", line 22, in main_page_open\n    driver.get(MainPageLinks.URL_MAIN_PAGE)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "driver",
        "value" : "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"a6a7f766bfb45ce31967e836cc69d5f7\")>"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  }, {
    "name" : "clear_allure_results_folder",
    "time" : {
      "start" : 1728697167335,
      "stop" : 1728697167335,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "driver::0",
    "time" : {
      "start" : 1728697356135,
      "stop" : 1728697356197,
      "duration" : 62
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Речевые упражнения."
  }, {
    "name" : "epic",
    "value" : "Speech exercises."
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "subSuite",
    "value" : "TestCardsRU"
  }, {
    "name" : "host",
    "value" : "fv-az570-490"
  }, {
    "name" : "thread",
    "value" : "2304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_speech_exercises_ru"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 8,
        "passed" : 52,
        "unknown" : 0,
        "total" : 60
      },
      "items" : [ {
        "uid" : "1487344d0d90f31c",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/59//#testresult/1487344d0d90f31c",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=129.0.6668.89)\nStacktrace:\n#0 0x55a3ab39302a <unknown>\n#1 0x55a3ab0795e0 <unknown>\n#2 0x55a3ab0717eb <unknown>\n#3 0x55a3ab061a09 <unknown>\n#4 0x55a3ab063744 <unknown>\n#5 0x55a3ab061cbd <unknown>\n#6 0x55a3ab06152f <unknown>\n#7 0x55a3ab061422 <unknown>\n#8 0x55a3ab05f493 <unknown>\n#9 0x55a3ab05fada <unknown>\n#10 0x55a3ab07bf41 <unknown>\n#11 0x55a3ab10d8c5 <unknown>\n#12 0x55a3ab0edb22 <unknown>\n#13 0x55a3ab10cd7d <unknown>\n#14 0x55a3ab0ed8c3 <unknown>\n#15 0x55a3ab0bb6b3 <unknown>\n#16 0x55a3ab0bc68e <unknown>\n#17 0x55a3ab35da2b <unknown>\n#18 0x55a3ab3619b1 <unknown>\n#19 0x55a3ab34a225 <unknown>\n#20 0x55a3ab362532 <unknown>\n#21 0x55a3ab32f38f <unknown>\n#22 0x55a3ab381f28 <unknown>\n#23 0x55a3ab3820f3 <unknown>\n#24 0x55a3ab391e7c <unknown>\n#25 0x7fa0a9694ac3 <unknown>",
        "time" : {
          "start" : 1728611046137,
          "stop" : 1728611046137,
          "duration" : 0
        }
      }, {
        "uid" : "6f88157fde1bd382",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/58//#testresult/6f88157fde1bd382",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728525181031,
          "stop" : 1728525191914,
          "duration" : 10883
        }
      }, {
        "uid" : "114ec0e0bc7825c3",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/57//#testresult/114ec0e0bc7825c3",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728438849516,
          "stop" : 1728438859693,
          "duration" : 10177
        }
      }, {
        "uid" : "97b0a85d2929f253",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/56//#testresult/97b0a85d2929f253",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728352450744,
          "stop" : 1728352461333,
          "duration" : 10589
        }
      }, {
        "uid" : "87e172857f5d3b08",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/55//#testresult/87e172857f5d3b08",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Can't find element by locator https://brainup.site/groups",
        "time" : {
          "start" : 1728267220340,
          "stop" : 1728267220340,
          "duration" : 0
        }
      }, {
        "uid" : "abbd6020b0bdb8e2",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/54//#testresult/abbd6020b0bdb8e2",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728179989570,
          "stop" : 1728179999850,
          "duration" : 10280
        }
      }, {
        "uid" : "a527870d2f4e5dee",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/53//#testresult/a527870d2f4e5dee",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728093261357,
          "stop" : 1728093273271,
          "duration" : 11914
        }
      }, {
        "uid" : "3ab8bc2ed7ded528",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/52//#testresult/3ab8bc2ed7ded528",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1728006965870,
          "stop" : 1728006977339,
          "duration" : 11469
        }
      }, {
        "uid" : "d2cfca76d928cf71",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/51//#testresult/d2cfca76d928cf71",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727920721007,
          "stop" : 1727920733116,
          "duration" : 12109
        }
      }, {
        "uid" : "4c0c57ba9d05f9c8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/50//#testresult/4c0c57ba9d05f9c8",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727834082001,
          "stop" : 1727834116029,
          "duration" : 34028
        }
      }, {
        "uid" : "a1c96b238c273778",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/49//#testresult/a1c96b238c273778",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727748217753,
          "stop" : 1727748228647,
          "duration" : 10894
        }
      }, {
        "uid" : "e05a685593df0475",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/48//#testresult/e05a685593df0475",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727661497341,
          "stop" : 1727661508738,
          "duration" : 11397
        }
      }, {
        "uid" : "674e6058ca871d19",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/47//#testresult/674e6058ca871d19",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727575392927,
          "stop" : 1727575418760,
          "duration" : 25833
        }
      }, {
        "uid" : "d1954782a524e7de",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/46//#testresult/d1954782a524e7de",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727488597707,
          "stop" : 1727488608200,
          "duration" : 10493
        }
      }, {
        "uid" : "89984d5fd8cdd4fe",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/45//#testresult/89984d5fd8cdd4fe",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727402354248,
          "stop" : 1727402366970,
          "duration" : 12722
        }
      }, {
        "uid" : "598baa7fa04aaaf9",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/44//#testresult/598baa7fa04aaaf9",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727315877659,
          "stop" : 1727315900345,
          "duration" : 22686
        }
      }, {
        "uid" : "5b3dbed2fdf91df8",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/43//#testresult/5b3dbed2fdf91df8",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727229507839,
          "stop" : 1727229520755,
          "duration" : 12916
        }
      }, {
        "uid" : "de384bd91f01d080",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/42//#testresult/de384bd91f01d080",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1727142966282,
          "stop" : 1727142979822,
          "duration" : 13540
        }
      }, {
        "uid" : "927d58af1c918f49",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/41//#testresult/927d58af1c918f49",
        "status" : "skipped",
        "statusDetails" : "XFAIL\n\nselenium.common.exceptions.TimeoutException: Message: Url: https://brainup.site/groups/2/series/3/subgroup/54/exercise/1294 has not been changed!!!",
        "time" : {
          "start" : 1727056359994,
          "stop" : 1727056386085,
          "duration" : 26091
        }
      }, {
        "uid" : "b1087f1be49604f7",
        "reportUrl" : "https://lambotik.github.io/auto-tests-python/40//#testresult/b1087f1be49604f7",
        "status" : "passed",
        "statusDetails" : "XPASS",
        "time" : {
          "start" : 1726970288203,
          "stop" : 1726970298059,
          "duration" : 9856
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail" ]
  },
  "source" : "34f54c83c5e8df92.json",
  "parameterValues" : [ ]
}